language: php
php:
  # Deployed on Toolforge with backend=webservice2:kubernetes/php7.2
  - "7.2"
  - "7.3"
install:
  - composer install
  # Upgrade from default Node.js version in Travis' PHP image to 10.x
  - curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.35.0/install.sh | bash
  - source ~/.nvm/nvm.sh; nvm install 10
script:
  - composer test
notifications:
  irc:
    channels:
      - "chat.freenode.net#mediawiki-i18n"
    template:
      - "%{repository}#%{build_number} (%{branch} - %{commit}: %{author}) %{message} - %{build_url}"
